const { Client } = require('pg');

const foods = [
  // Cereais e derivados
  {
    food_number: 1,
    category: 'Cereais e derivados',
    description: 'Arroz, integral, cozido',
    humidity_pct: 70.1,
    energy_kcal: 124,
    energy_kj: 517,
    protein_g: 2.6,
    lipid_g: 1.0,
    cholesterol_mg: 0,
    carbohydrate_g: 25.8,
    fiber_g: 2.7,
    ash_g: 0.5,
    calcium_mg: 5,
    magnesium_mg: 59,
    manganese_mg: 0.63,
    phosphorus_mg: 106,
    iron_mg: 0.3,
    sodium_mg: 1,
    potassium_mg: 75,
    copper_mg: 0.02,
    zinc_mg: 0.7,
    retinol_mcg: 0,
    thiamine_mg: 0.08,
    riboflavin_mg: 0,
    pyridoxine_mg: 0.08,
    niacin_mg: 0,
    vit_c_mg: 0
  },
  {
    food_number: 2,
    category: 'Cereais e derivados',
    description: 'Arroz, integral, cru',
    humidity_pct: 12.2,
    energy_kcal: 360,
    energy_kj: 1505,
    protein_g: 7.3,
    lipid_g: 1.9,
    cholesterol_mg: 0,
    carbohydrate_g: 77.5,
    fiber_g: 4.8,
    ash_g: 1.2,
    calcium_mg: 8,
    magnesium_mg: 110,
    manganese_mg: 2.99,
    phosphorus_mg: 251,
    iron_mg: 0.9,
    sodium_mg: 2,
    potassium_mg: 173,
    copper_mg: 0.07,
    zinc_mg: 1.4,
    retinol_mcg: 0,
    thiamine_mg: 0.26,
    riboflavin_mg: 0,
    pyridoxine_mg: 0.18,
    niacin_mg: 4.18,
    vit_c_mg: 0
  },
  {
    food_number: 3,
    category: 'Cereais e derivados',
    description: 'Arroz, tipo 1, cozido',
    humidity_pct: 69.1,
    energy_kcal: 128,
    energy_kj: 537,
    protein_g: 2.5,
    lipid_g: 0.2,
    cholesterol_mg: 0,
    carbohydrate_g: 28.1,
    fiber_g: 1.6,
    ash_g: 0.1,
    calcium_mg: 4,
    magnesium_mg: 2,
    manganese_mg: 0.30,
    phosphorus_mg: 18,
    iron_mg: 0.1,
    sodium_mg: 1,
    potassium_mg: 15,
    copper_mg: 0.02,
    zinc_mg: 0.5,
    retinol_mcg: 0,
    thiamine_mg: 0,
    riboflavin_mg: 0,
    pyridoxine_mg: 0,
    niacin_mg: 0,
    vit_c_mg: 0
  },
  {
    food_number: 7,
    category: 'Cereais e derivados',
    description: 'Aveia, flocos, crua',
    humidity_pct: 9.1,
    energy_kcal: 394,
    energy_kj: 1648,
    protein_g: 13.9,
    lipid_g: 8.5,
    cholesterol_mg: 0,
    carbohydrate_g: 66.6,
    fiber_g: 9.1,
    ash_g: 1.8,
    calcium_mg: 48,
    magnesium_mg: 119,
    manganese_mg: 1.89,
    phosphorus_mg: 153,
    iron_mg: 4.4,
    sodium_mg: 5,
    potassium_mg: 336,
    copper_mg: 0.44,
    zinc_mg: 2.6,
    retinol_mcg: 0,
    thiamine_mg: 0.55,
    riboflavin_mg: 0.03,
    pyridoxine_mg: 0,
    niacin_mg: 4.47,
    vit_c_mg: 1.4
  },
  {
    food_number: 13,
    category: 'Cereais e derivados',
    description: 'Biscoito, salgado, cream cracker',
    humidity_pct: 4.1,
    energy_kcal: 432,
    energy_kj: 1806,
    protein_g: 10.1,
    lipid_g: 14.4,
    cholesterol_mg: 0,
    carbohydrate_g: 68.7,
    fiber_g: 2.5,
    ash_g: 2.7,
    calcium_mg: 20,
    magnesium_mg: 40,
    manganese_mg: 0.69,
    phosphorus_mg: 148,
    iron_mg: 2.2,
    sodium_mg: 854,
    potassium_mg: 181,
    copper_mg: 0.18,
    zinc_mg: 1.1,
    retinol_mcg: 0,
    thiamine_mg: 0.71,
    riboflavin_mg: 0.13,
    pyridoxine_mg: 0.17,
    niacin_mg: 7.14,
    vit_c_mg: 0
  },
  {
    food_number: 35,
    category: 'Cereais e derivados',
    description: 'Farinha, de trigo',
    humidity_pct: 13.0,
    energy_kcal: 360,
    energy_kj: 1508,
    protein_g: 9.8,
    lipid_g: 1.4,
    cholesterol_mg: 0,
    carbohydrate_g: 75.1,
    fiber_g: 2.3,
    ash_g: 0.8,
    calcium_mg: 18,
    magnesium_mg: 31,
    manganese_mg: 0.46,
    phosphorus_mg: 115,
    iron_mg: 1.0,
    sodium_mg: 1,
    potassium_mg: 151,
    copper_mg: 0.15,
    zinc_mg: 0.8,
    retinol_mcg: 0,
    thiamine_mg: 0.31,
    riboflavin_mg: 0,
    pyridoxine_mg: 0,
    niacin_mg: 0.89,
    vit_c_mg: 0
  },
  {
    food_number: 53,
    category: 'Cereais e derivados',
    description: 'Pão, trigo, francês',
    humidity_pct: 28.5,
    energy_kcal: 300,
    energy_kj: 1254,
    protein_g: 8.0,
    lipid_g: 3.1,
    cholesterol_mg: 0,
    carbohydrate_g: 58.6,
    fiber_g: 2.3,
    ash_g: 1.8,
    calcium_mg: 16,
    magnesium_mg: 25,
    manganese_mg: 0.46,
    phosphorus_mg: 95,
    iron_mg: 1.0,
    sodium_mg: 648,
    potassium_mg: 142,
    copper_mg: 0.13,
    zinc_mg: 0.8,
    retinol_mcg: 0,
    thiamine_mg: 0.39,
    riboflavin_mg: 0.67,
    pyridoxine_mg: 0.60,
    niacin_mg: 2.34,
    vit_c_mg: 0
  },
  // Ovos e derivados
  {
    food_number: 488,
    category: 'Ovos e derivados',
    description: 'Ovo, de galinha, inteiro, cozido/10minutos',
    humidity_pct: 75.8,
    energy_kcal: 146,
    energy_kj: 610,
    protein_g: 13.3,
    lipid_g: 9.5,
    cholesterol_mg: 397,
    carbohydrate_g: 0.6,
    fiber_g: 0,
    ash_g: 0.8,
    calcium_mg: 49,
    magnesium_mg: 11,
    manganese_mg: 0.02,
    phosphorus_mg: 184,
    iron_mg: 1.5,
    sodium_mg: 146,
    potassium_mg: 139,
    copper_mg: 0.04,
    zinc_mg: 1.2,
    retinol_mcg: 32,
    thiamine_mg: 0.08,
    riboflavin_mg: 0.30,
    pyridoxine_mg: 0,
    niacin_mg: 0,
    vit_c_mg: 0
  },
  {
    food_number: 489,
    category: 'Ovos e derivados',
    description: 'Ovo, de galinha, inteiro, cru',
    humidity_pct: 75.6,
    energy_kcal: 143,
    energy_kj: 599,
    protein_g: 13.0,
    lipid_g: 8.9,
    cholesterol_mg: 356,
    carbohydrate_g: 1.6,
    fiber_g: 0,
    ash_g: 0.8,
    calcium_mg: 42,
    magnesium_mg: 13,
    manganese_mg: 0,
    phosphorus_mg: 164,
    iron_mg: 1.6,
    sodium_mg: 168,
    potassium_mg: 150,
    copper_mg: 0.06,
    zinc_mg: 1.1,
    retinol_mcg: 79,
    thiamine_mg: 0.07,
    riboflavin_mg: 0.58,
    pyridoxine_mg: 0,
    niacin_mg: 0.75,
    vit_c_mg: 0
  },
  // Verduras, hortaliças e derivados
  {
    food_number: 70,
    category: 'Verduras, hortaliças e derivados',
    description: 'Abobrinha, italiana, cozida',
    humidity_pct: 95.3,
    energy_kcal: 15,
    energy_kj: 63,
    protein_g: 1.1,
    lipid_g: 0.2,
    cholesterol_mg: 0,
    carbohydrate_g: 3.0,
    fiber_g: 1.6,
    ash_g: 0.4,
    calcium_mg: 17,
    magnesium_mg: 17,
    manganese_mg: 0.11,
    phosphorus_mg: 22,
    iron_mg: 0.2,
    sodium_mg: 1,
    potassium_mg: 126,
    copper_mg: 0.01,
    zinc_mg: 0.3,
    retinol_mcg: 0,
    thiamine_mg: 0.05,
    riboflavin_mg: 0,
    pyridoxine_mg: 0.06,
    niacin_mg: 0,
    vit_c_mg: 2.1
  },
  {
    food_number: 91,
    category: 'Verduras, hortaliças e derivados',
    description: 'Batata, inglesa, cozida',
    humidity_pct: 86.4,
    energy_kcal: 52,
    energy_kj: 216,
    protein_g: 1.2,
    lipid_g: 0.1,
    cholesterol_mg: 0,
    carbohydrate_g: 11.9,
    fiber_g: 1.3,
    ash_g: 0.5,
    calcium_mg: 4,
    magnesium_mg: 5,
    manganese_mg: 0.07,
    phosphorus_mg: 24,
    iron_mg: 0.2,
    sodium_mg: 2,
    potassium_mg: 161,
    copper_mg: 0.06,
    zinc_mg: 0.2,
    retinol_mcg: 0,
    thiamine_mg: 0.05,
    riboflavin_mg: 0,
    pyridoxine_mg: 0.08,
    niacin_mg: 0,
    vit_c_mg: 3.8
  },
  {
    food_number: 107,
    category: 'Verduras, hortaliças e derivados',
    description: 'Cebola, crua',
    humidity_pct: 88.9,
    energy_kcal: 39,
    energy_kj: 165,
    protein_g: 1.7,
    lipid_g: 0.1,
    cholesterol_mg: 0,
    carbohydrate_g: 8.9,
    fiber_g: 2.2,
    ash_g: 0.4,
    calcium_mg: 14,
    magnesium_mg: 12,
    manganese_mg: 0.13,
    phosphorus_mg: 38,
    iron_mg: 0.2,
    sodium_mg: 1,
    potassium_mg: 176,
    copper_mg: 0.05,
    zinc_mg: 0.2,
    retinol_mcg: 0,
    thiamine_mg: 0.04,
    riboflavin_mg: 0,
    pyridoxine_mg: 0.14,
    niacin_mg: 0,
    vit_c_mg: 4.7
  },
  // Frutas e derivados
  {
    food_number: 163,
    category: 'Frutas e derivados',
    description: 'Abacate, cru',
    humidity_pct: 83.8,
    energy_kcal: 96,
    energy_kj: 402,
    protein_g: 1.2,
    lipid_g: 8.4,
    cholesterol_mg: 0,
    carbohydrate_g: 6.0,
    fiber_g: 6.3,
    ash_g: 0.5,
    calcium_mg: 8,
    magnesium_mg: 15,
    manganese_mg: 0.17,
    phosphorus_mg: 22,
    iron_mg: 0.2,
    sodium_mg: 0,
    potassium_mg: 206,
    copper_mg: 0.15,
    zinc_mg: 0.2,
    retinol_mcg: 0,
    thiamine_mg: 0,
    riboflavin_mg: 0.04,
    pyridoxine_mg: 0,
    niacin_mg: 0,
    vit_c_mg: 8.7
  },
  {
    food_number: 179,
    category: 'Frutas e derivados',
    description: 'Banana, nanica, crua',
    humidity_pct: 73.8,
    energy_kcal: 92,
    energy_kj: 383,
    protein_g: 1.4,
    lipid_g: 0.1,
    cholesterol_mg: 0,
    carbohydrate_g: 23.8,
    fiber_g: 1.9,
    ash_g: 0.8,
    calcium_mg: 3,
    magnesium_mg: 28,
    manganese_mg: 0.14,
    phosphorus_mg: 27,
    iron_mg: 0.3,
    sodium_mg: 0,
    potassium_mg: 376,
    copper_mg: 0.10,
    zinc_mg: 0.2,
    retinol_mcg: 0,
    thiamine_mg: 0.05,
    riboflavin_mg: 0.02,
    pyridoxine_mg: 0.14,
    niacin_mg: 0,
    vit_c_mg: 5.9
  },
  // Carnes e derivados
  {
    food_number: 401,
    category: 'Carnes e derivados',
    description: 'Frango, filé, à milanesa',
    humidity_pct: 54.9,
    energy_kcal: 221,
    energy_kj: 924,
    protein_g: 28.5,
    lipid_g: 7.8,
    cholesterol_mg: 84,
    carbohydrate_g: 7.5,
    fiber_g: 1.1,
    ash_g: 1.3,
    calcium_mg: 9,
    magnesium_mg: 35,
    manganese_mg: 0.06,
    phosphorus_mg: 249,
    iron_mg: 1.1,
    sodium_mg: 122,
    potassium_mg: 408,
    copper_mg: 0.05,
    zinc_mg: 0.8,
    retinol_mcg: 7,
    thiamine_mg: 0.05,
    riboflavin_mg: 0.04,
    pyridoxine_mg: 0.52,
    niacin_mg: 11.07,
    vit_c_mg: 0
  },
  {
    food_number: 377,
    category: 'Carnes e derivados',
    description: 'Carne, bovina, patinho, sem gordura, grelhado',
    humidity_pct: 55.2,
    energy_kcal: 219,
    energy_kj: 917,
    protein_g: 35.9,
    lipid_g: 7.3,
    cholesterol_mg: 126,
    carbohydrate_g: 0,
    fiber_g: 0,
    ash_g: 1.3,
    calcium_mg: 5,
    magnesium_mg: 27,
    manganese_mg: 0.02,
    phosphorus_mg: 289,
    iron_mg: 3.0,
    sodium_mg: 60,
    potassium_mg: 421,
    copper_mg: 0.12,
    zinc_mg: 8.1,
    retinol_mcg: 0,
    thiamine_mg: 0.04,
    riboflavin_mg: 0.03,
    pyridoxine_mg: 0,
    niacin_mg: 3.01,
    vit_c_mg: 0
  },
  // Leite e derivados
  {
    food_number: 459,
    category: 'Leite e derivados',
    description: 'Leite, de vaca, integral, pó',
    humidity_pct: 2.7,
    energy_kcal: 497,
    energy_kj: 2078,
    protein_g: 25.4,
    lipid_g: 26.9,
    cholesterol_mg: 85,
    carbohydrate_g: 39.2,
    fiber_g: 0,
    ash_g: 5.8,
    calcium_mg: 890,
    magnesium_mg: 77,
    manganese_mg: 0,
    phosphorus_mg: 1242,
    iron_mg: 0.5,
    sodium_mg: 323,
    potassium_mg: 1132,
    copper_mg: 0.11,
    zinc_mg: 2.7,
    retinol_mcg: 361,
    thiamine_mg: 0.24,
    riboflavin_mg: 1.03,
    pyridoxine_mg: 0,
    niacin_mg: 0,
    vit_c_mg: 0
  },
  {
    food_number: 463,
    category: 'Leite e derivados',
    description: 'Queijo, mozarela',
    humidity_pct: 45.3,
    energy_kcal: 330,
    energy_kj: 1380,
    protein_g: 22.6,
    lipid_g: 25.2,
    cholesterol_mg: 80,
    carbohydrate_g: 3.0,
    fiber_g: 0,
    ash_g: 3.8,
    calcium_mg: 875,
    magnesium_mg: 24,
    manganese_mg: 0.03,
    phosphorus_mg: 470,
    iron_mg: 0.3,
    sodium_mg: 581,
    potassium_mg: 62,
    copper_mg: 0.08,
    zinc_mg: 3.5,
    retinol_mcg: 109,
    thiamine_mg: 0,
    riboflavin_mg: 0.20,
    pyridoxine_mg: 0,
    niacin_mg: 0,
    vit_c_mg: 0
  }
];

async function seed() {
  const client = new Client({
    connectionString: 'postgresql://postgres:3BoPuMwf7vHL6HVq@db.wkngjvsgafmdwejmckks.supabase.co:5432/postgres',
    ssl: { rejectUnauthorized: false }
  });

  try {
    await client.connect();
    console.log('✅ Conectado ao banco de dados Postgres!');

    for (const food of foods) {
      await client.query(`
        INSERT INTO public.taco_foods (
          food_number, category, description, humidity_pct, energy_kcal, energy_kj,
          protein_g, lipid_g, cholesterol_mg, carbohydrate_g, fiber_g, ash_g,
          calcium_mg, magnesium_mg, manganese_mg, phosphorus_mg, iron_mg, sodium_mg,
          potassium_mg, copper_mg, zinc_mg, retinol_mcg, thiamine_mg, riboflavin_mg,
          pyridoxine_mg, niacin_mg, vit_c_mg
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27
        ) ON CONFLICT (food_number) DO UPDATE SET
          category = EXCLUDED.category,
          description = EXCLUDED.description,
          energy_kcal = EXCLUDED.energy_kcal,
          protein_g = EXCLUDED.protein_g,
          lipid_g = EXCLUDED.lipid_g,
          carbohydrate_g = EXCLUDED.carbohydrate_g,
          sodium_mg = EXCLUDED.sodium_mg
      `, [
        food.food_number, food.category, food.description, food.humidity_pct, food.energy_kcal, food.energy_kj,
        food.protein_g, food.lipid_g, food.cholesterol_mg, food.carbohydrate_g, food.fiber_g, food.ash_g,
        food.calcium_mg, food.magnesium_mg, food.manganese_mg, food.phosphorus_mg, food.iron_mg, food.sodium_mg,
        food.potassium_mg, food.copper_mg, food.zinc_mg, food.retinol_mcg, food.thiamine_mg, food.riboflavin_mg,
        food.pyridoxine_mg, food.niacin_mg, food.vit_c_mg
      ]);
    }

    console.log(`✅ ${foods.length} alimentos da tabela TACO semeados com sucesso!`);
  } catch (err) {
    console.error('❌ Erro no seeding:', err);
  } finally {
    await client.end();
  }
}

seed();
